services:
  miniflux:
    image: miniflux/miniflux:2.2.15
    container_name: miniflux
    restart: unless-stopped
    depends_on:
      miniflux-postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@miniflux-postgres/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - PORT=8080
      - MEDIA_PROXY_MODE=all
      - BATCH_SIZE=1000
      - WORKER_POOL_SIZE=50
      - HTTP_CLIENT_TIMEOUT=300
    env_file:
      - env

  miniflux-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

  miniflux-postgres-backup:
    image: ghcr.io/sekai-soft/postgres-backup-s3:15
    restart: unless-stopped
    env_file:
      - env-backup
      - /home/nixos/env-backup
    environment:
      S3_PREFIX: 'miniflux'
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 14
      POSTGRES_HOST: miniflux-postgres
      POSTGRES_DATABASE: miniflux
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: secret

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run miniflux
    env_file:
      - env
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  miniflux-postgres:
