name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ops

      - name: "[gibraltar] Pull repo"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@gibraltar" "cd /home/nixos/os-config && git checkout -- . && git fetch origin && git checkout ${{ github.sha }}"
      - name: "[gibraltar] Run os-apply"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@gibraltar" "bash /home/nixos/os-config/os-apply"
      - name: "[gibraltar] Run apps-apply"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@gibraltar" "bash /home/nixos/os-config/apps-apply"
      - name: "[gibraltar] Run jobs-apply"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@gibraltar" "bash /home/nixos/os-config/jobs-apply"

      - name: "[numbani] Pull repo"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@numbani" "cd /home/nixos/os-config && git checkout -- . && git fetch origin && git checkout ${{ github.sha }}"
      - name: "[numbani] Run os-apply"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@numbani" "bash /home/nixos/os-config/os-apply"
      - name: "[numbani] Run apps-apply"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@numbani" "bash /home/nixos/os-config/apps-apply"
      - name: "[numbani] Run jobs-apply"
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "nixos@numbani" "bash /home/nixos/os-config/jobs-apply"